### ISSUE TITLE
ModuleNotFoundError: No module named 'npu_compiler.session'

### ISSUE THREAD

**Issue by yyj2013** [NationalChip/gxDNN#8]
env: Anconda python=3.5
pip install npu_compiler success;
run 'gxnpuc --version' failed;
log:
  File "/home/username/anaconda3/bin/gxnpuc", line 5, in <module>
    import npu_compiler
  File "/home/username/anaconda3/lib/python3.6/site-packages/npu_compiler/__init__.py", line 3, in <module>
    from npu_compiler.session import Session
ModuleNotFoundError: No module named 'npu_compiler.session'

**Comment by vv1133** [comment]
目前npu_compiler只支持python2.7和python3.5版本

**Comment by vv1133** [comment]
> env: Anconda python=3.5pip install npu_compiler success;run 'gxnpuc --version' failed;log:File "/home/username/anaconda3/bin/gxnpuc", line 5, in import npu_compilerFile "/home/username/anaconda3/lib/python3.6/site-packages/npu_compiler/init.py", line 3, in from npu_compiler.session import SessionModuleNotFoundError: No module named 'npu_compiler.session'

目前npu_compiler只支持python2.7和python3.5版本

**Comment by yyj2013** [comment]
ok，测试2.7正常。
